# Generated by Django 2.2.1 on 2019-05-09 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_task'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='company_name',
            new_name='description',
        ),
    ]
