# Generated by Django 2.2.1 on 2019-05-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190509_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(default='TODO', max_length=500),
        ),
    ]
